# Generated by Django 3.0 on 2021-12-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='Posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Posts'),
        ),
    ]
