# Generated by Django 3.0 on 2021-12-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211218_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ('date_added',)},
        ),
        migrations.AddField(
            model_name='comentarios',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
