# Generated by Django 3.0 on 2021-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211219_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
